default:
    trainer: ppo
    beta: 5.0e-2
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e5
    memory_size: 256
    num_epoch: 3
    num_layers: 2
    time_horizon: 32
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
    normalize: true
    hidden_units: 64
    batch_size: 10
    buffer_size: 100